# Generated by Django 6.1 on 2026-10-04 21:11

from django.db import migrations, models


def fijar_rol_administrador(apps, schema_editor):
    Login = apps.get_model('Cotizador', 'Login')
    Login.objects.all().update(rol='Administrador CINTAC')


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='rol',
            field=models.CharField(default='Administrador CINTAC', editable=False, max_length=50),
        ),
        migrations.RunPython(fijar_rol_administrador, migrations.RunPython.noop),
    ]
