# Generated by Django 6.1 on 2026-10-04 23:46

import Cotizador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizador', '0002_alter_login_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=50, validators=[Cotizador.models.validate_login_password]),
        ),
    ]
