# Generated by Django 6.1 on 2026-10-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizador', '0003_alter_login_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ruta_logistica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puerto_origen', models.CharField(choices=[('China', 'China'), ('Japon', 'Japon'), ('España', 'España'), ('EE.UU', 'EE.UU'), ('Perú', 'Perú')], max_length=100)),
                ('puerto_destino', models.CharField(max_length=100)),
                ('dias_transito', models.IntegerField()),
            ],
        ),
    ]
