# Generated by Django 6.1 on 2026-10-06 00:33

import Cotizador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizador', '0004_ruta_logistica_alter_login_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=100, validators=[Cotizador.models.validate_login_email]),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=50, validators=[Cotizador.models.validate_login_username]),
        ),
    ]
