# Generated by Django 6.1 on 2026-10-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizador', '0006_alter_ruta_logistica_puerto_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta_logistica',
            name='puerto_destino',
            field=models.CharField(choices=[('Valparaíso, Chile', 'Valparaíso, Chile'), ('San Antonio, Chile', 'San Antonio, Chile')], max_length=100),
        ),
    ]
