# Generated by Django 6.1 on 2026-10-06 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizador', '0007_alter_ruta_logistica_puerto_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarifa_contenedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contenedor', models.CharField(choices=[('20 HQ', '20 HQ'), ('40 HQ', '40 HQ')], max_length=50)),
                ('peso_max', models.IntegerField(choices=[('20 HQ', 20000), ('40 HQ', 25000)])),
                ('costo_fijo', models.IntegerField()),
                ('moneda_original', models.CharField(default='USD', max_length=10)),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cotizador.ruta_logistica')),
            ],
        ),
    ]
