# Generated by Django 6.1 on 2026-10-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizador', '0008_tarifa_contenedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa_contenedor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarifa_contenedor',
            name='peso_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tarifa_contenedor',
            name='tipo_contenedor',
            field=models.CharField(max_length=50),
        ),
    ]
