# Generated by Django 6.1 on 2026-10-06 02:56

import Cotizador.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizador', '0009_alter_tarifa_contenedor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cotizacion_generada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_cliente', models.CharField(max_length=100, validators=[Cotizador.models.valida_nombre])),
                ('empresa', models.CharField(max_length=100, validators=[Cotizador.models.valida_empresa])),
                ('correo_cliente', models.CharField(max_length=100, validators=[Cotizador.models.validate_login_email])),
                ('descripcion_carga', models.TextField()),
                ('peso_ingresado_kg', models.IntegerField()),
                ('tipo_contenedor', models.CharField(max_length=50)),
                ('cantidad_contenedores', models.IntegerField()),
                ('monto_IVA', models.IntegerField()),
                ('monto_total', models.IntegerField()),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cotizador.ruta_logistica')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cotizador.login')),
            ],
        ),
    ]
